const ACTIONS = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILED: 'REGISTER_FAILED',
    LOGOUT: 'LOGOUT',
    FETCH_USER_COMPLETE: 'FETCH_USER_COMPLETE',
    FETCH_USER_FAILED: 'FETCH_USER_FAILED',
    SET_LOADING: 'SET_LOADING',
    NEXT_PAGE: 'NEXT_PAGE',
    FETCH_LIST_PARTNER_COMPLETE: 'FETCH_LIST_PARTNER_COMPLETE',
    FETCH_LIST_PARTNER_FAILED: 'FETCH_LIST_PARTNER_FAILED'
}

export default ACTIONS;